### PR TITLE
Support Code Lens

### LINKED ISSUE #56: Codelens option to start Tests
Abstract:
From my understanding a codelens option is a clickable link in your code, which could enable you to start jest in run or debug mode.

### PR DESCRIPTION
**Pull request by EstefaniaGuardado**
Resolves #56

### CODE REVIEW

**Comment by firsttris** [comment]
Hey @EstefaniaGuardado 

great work, really appreciate your contributions.

i tested your pull request and it worked great!!

however i noticed that your are not using findFullTestName (utils.ts) to construct the full test path name when i click the codelens options.

that means in some situation it will not execute the test instead skip it

see this example:
image

regards
Tristan

**Comment by firsttris** [comment]
while i run this test with the "Run Jest" option it will construct the full test path:
image

**Comment by EstefaniaGuardado** [comment]
Hi @firsttris 

Thank you very much for the feedback! I have just applied it.

**Comment by firsttris** [comment]
Hey @EstefaniaGuardado 

thx very much for your great work!

i will create new release

**Comment by jquense** [comment]
love this option but am finding it hard to keep on, because it shifts the code around A LOT while typing out tests. Any time the code is unparsable while typing the code lens links disappear and then reappear as soon as the code is valid. This causes everything to shift really dramatically while writing tests. I wonder if there is some way to keep the buttons even when code is invalid?

**Pull request merged**
