### PR TITLE
Update jest-editor-support, fix CI

### PR DESCRIPTION
**Pull request by nirgilboa**
Changes included:
1. Upgrade `jest-editor-support` to fix Typescript compilation errors
2. Add a `test-compile` step to GitHub Workflow
3. Use MacOS for GitHub Workflow (which runs headless tests oob)

Currently still facing the following error when running the tests, seems to be caused by: https://github.com/facebook/jest/issues/12398
```
TypeError: Cannot assign to read only property 'write' of object '#<Socket>'
	at DefaultReporter.__wrapStdio (/Users/runner/work/vscode-jest-runner/vscode-jest-runner/node_modules/@jest/reporters/build/DefaultReporter.js:139:18)
	at new DefaultReporter (/Users/runner/work/vscode-jest-runner/vscode-jest-runner/node_modules/@jest/reporters/build/DefaultReporter.js:90:10)
	at TestScheduler._setupDefaultReporters (/Users/runner/work/vscode-jest-runner/vscode-jest-runner/node_modules/@jest/core/build/TestScheduler.js:[45](https://github.com/firsttris/vscode-jest-runner/runs/5346425815?check_suite_focus=true#step:7:45)6:11)
	at TestScheduler._setupReporters (/Users/runner/work/vscode-jest-runner/vscode-jest-runner/node_modules/@jest/core/build/TestScheduler.js:415:12)
	at createTestScheduler (/Users/runner/work/vscode-jest-runner/vscode-jest-runner/node_modules/@jest/core/build/TestScheduler.js:114:19)
	at runJest (/Users/runner/work/vscode-jest-runner/vscode-jest-runner/node_modules/@jest/core/build/runJest.js:397:66)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async _run10000 (/Users/runner/work/vscode-jest-runner/vscode-jest-runner/node_modules/@jest/core/build/cli/index.js:320:7)
	at async runCLI (/Users/runner/work/vscode-jest-runner/vscode-jest-runner/node_modules/@jest/core/build/cli/index.js:173:3)
```

### CODE REVIEW

**Comment by F3n67u** [comment]
It's fixed by vscode team, see https://github.com/microsoft/vscode/commit/6f0c1b068a84ddf1c06cac054873ac7a8b5ff3ba

**Comment by nirgilboa** [comment]
> It's fixed by vscode team, see [microsoft/vscode@6f0c1b0](https://github.com/microsoft/vscode/commit/6f0c1b068a84ddf1c06cac054873ac7a8b5ff3ba)

Thanks for this! 🙏🏻  will wait for a new vscode version

**Comment by Cellule** [comment]
I think this extension packs wayyy too much of `jest-editor-support` when it only needs the parser
I made a new `parser.ts` file that only imports the parser and the build is much faster, avoids all these other issues and resulting extension file is much smaller (1.22MiB vs 5.43MiB in development)

```ts
// parser.ts
import type { ParsedNode } from 'jest-editor-support';
import parse from 'jest-editor-support/build/parsers';

export { parse, ParsedNode };
```

then all imports to `jest-editor-support` is replaced by `./parser`

**Comment by nirgilboa** [comment]
@firsttris Build is now green 🎉 as it runs with vscode 1.65.0 which contains the bugfix we needed (https://github.com/microsoft/vscode/releases/tag/1.65.0)

**Pull request merged**
