### PR TITLE
Support param decorator

### PR DESCRIPTION
**Pull request by GP4cK**
Closes https://github.com/firsttris/vscode-jest-runner/issues/260

Upgraded `jest-editor-support` to support test files using param decorators

### CODE REVIEW

**Comment by GP4cK** [comment]
@firsttris not too sure how to write a test for this. I guess I could create a `TextDocument` with a test that contains a param decorator and check the result of `provideCodeLenses`. What do you think?

**Comment by firsttris** [comment]
hey @GP4cK, thx for your contribution.

will decorators: legacy disable some other feature? because "legacy decorators" sounds like theres also a newer option?

best regards
Tristan

**Comment by GP4cK** [comment]
> will decorators: legacy disable some other feature?

I don't think so. It will just load a plugin to support param decorators which are not supported in babel 7. See this issue: https://github.com/jest-community/jest-editor-support/issues/89#issuecomment-1179601980.

For what it's worth, I created a VSIX from my branch and I've been using it since I made the PR and haven't faced any problem.

**Comment by firsttris** [comment]
alry then lets merge it, sorry for the late response, was bussy with reallife stuff.

**Pull request merged**
