### PR TITLE
Added projectPath setting

### PR DESCRIPTION
**Pull request by Ranguna**
This PR allows projects that have the `node_modules` in a different subfolder other than the root workspace folder.

### CODE REVIEW

**Comment by Ranguna** [comment]
This will not work when users use predefined variables such as ${workspaceFolder}, because vscode extension API does not replace variables when extensions read from the config path. There are two open issues in vscode: https://github.com/microsoft/vscode/issues/2809 and https://github.com/microsoft/vscode/issues/46471 .

**Comment by firsttris** [comment]
@Ranguna thx for your contribution.

if you change still work in progress or why is the WIP left?

let me know when you are ready and i will include your changes in the next version.

**Comment by Ranguna** [comment]
Sorry for the delay. I completely forgot to remove the WIP status.
Could you please make sure if everything is ok ?

I changed some things in a few places but since you don't have tests, I'm not sure if I broke anything or if I changed all the necessary things.

**Comment by grit96** [comment]
This won't work with relative paths because it first changes to that directory but then also tries to use the path as a prefix for the jest path.

**Comment by firsttris** [comment]
thx for reporting @grit96

**Pull request merged**
