### PR TITLE
parse test name from line if selection is empty

### PR DESCRIPTION
**Pull request by krizzdewizz**
- use double quotes on windows
- selection may have quotes
- save editor before running test

### CODE REVIEW

**Comment by krizzdewizz** [comment]
Hi, thanks for your cool extension. I've tuned it a little bit to fit my needs and may others can benefit too.

**Comment by firsttris** [comment]
Hi @krizzdewizz 

thanks for the good work, i have tested it on my linux machine and i like it really much!

**Comment by firsttris** [comment]
Your PR is included in Version 0.2.3.

**Comment by krizzdewizz** [comment]
very cool, thanks a lot!

**Pull request merged**
