### PR TITLE
Keep Run/Debug buttons shown when failed to parse document

### PR DESCRIPTION
**Pull request by keroxp**
Run/Debug buttons will disappear when failed to parse document. This behaviour causes visual layout change repeatedly on editing test file. In most cases, there' re no problems for keeping buttons shown in previous position even if document has parsing errors. Pushing buttons simply ends with execution error in that situation.

**current**
[Image from Gyazo](https://gyazo.com/caea007b5a018d23e9743ed2ad2fbadf)

**after**
[Image from Gyazo](https://gyazo.com/c07e7abc66d40ab7d48a7c6dcd8ae852)

### CODE REVIEW

**Comment by firsttris** [comment]
hey @keroxp good work, thx for your contribution !

**Comment by firsttris** [comment]
hey @keroxp 

its seems some issues came up, take a look here: https://github.com/firsttris/vscode-jest-runner/issues/189

i removed the prevResults solution for now.

if you have an idea how to fix this, dont hesitate to create a new pr from master.

thx for your help

best regards
tristan

**Comment by firsttris** [comment]
there was another issue, probably also related to this approach:
https://github.com/firsttris/vscode-jest-runner/issues/180

**Comment by lishine** [comment]
the layout shift happens stilll...

**Pull request merged**
