### PR TITLE
support for external native terminal run

### PR DESCRIPTION
**Pull request by Avivbens**
* support for external native terminal run
* better source-map for debugging the lib
* set npmrc to force package load from NPM server
* prevent external terminal on debug mode

### CODE REVIEW

**Comment by firsttris** [comment]
hey @Avivbens 

i finally got it merged. 

sorry for taking so long, i was in the hospital for some weeks.

Do you want to become Collaborator in the Project? You would get full repo permissions. I need some help to take care of it.

best regards
Tristan

**Comment by Avivbens** [comment]
@firsttris 
Hi!
Hope you're better now 🙏

Sure, I can take a place on the repo, some product excellent changes are needed.

**Comment by firsttris** [comment]
invited

**Comment by firsttris** [comment]
@Avivbens 

theres a problem with your PR, the project no longer installs under Windows because of the ttab library you used.

can you change it to not use it? otherwise i have to revert this PR.

**Comment by Avivbens** [comment]
I'll find an alternative. 
For now, revert the PR so users can use it.

**Comment by firsttris** [comment]
i found we can let the user manually install ttab, and dont add it to dependencies fixes the problem.
since you only used it as cmd command.
see here: https://github.com/firsttris/vscode-jest-runner/commit/ac9d67d3b85578d43d256b22ce3bdc2b3e5cc3ce

**Pull request merged**
