### PR TITLE
Reset Terminal, Run Single Test improvements, JestComamnd

### PR DESCRIPTION
**Pull request by alexsotocx**
# Added

* Clear terminal each run
* Improve speed of test loading just by adding current file to the command, so It won't look for all the files.
* Improve test name selection, now you can run the command and it will select the closes `describe or it` looking up in the file

It will fix the next issue: https://github.com/firsttris/vscode-jest-runner/issues/8

### CODE REVIEW

**Comment by ricardovf** [comment]
this seems really good, but i could not run on my installation, nothing happens.

@firsttris any update on this, will you merge?

**Comment by firsttris** [comment]
hey guys, 

sorry i found no time to test, currently building a :house_with_garden:

but now i checked, and its also not working for me:
image

**Comment by ricardovf** [comment]
@alexsotocx this PR is promising, can you check?

> hey guys,
> 
> sorry i found no time to test, currently building a 🏡
Good luck!

**Comment by alexsotocx** [comment]
Yep I will check! for me it's working with my currents projects but I'm using a modified command. That's maybe the issue. I will post a video soon.

**Comment by alexsotocx** [comment]
I configure it to use npx jest, 
it will create commands like this one
`npx jest --verbose /Users/alexsotocx/Documents/projects/test-runner/specs/test.js -t 'TestRunner'`

workingv

**Comment by firsttris** [comment]
please do

i will test & merge

**Comment by ricardovf** [comment]
Great, thanks friends!

**Comment by alexsotocx** [comment]
The Pull request is fix! 👍

**Comment by ricardovf** [comment]
@firsttris can you merge this? 👍

**Comment by firsttris** [comment]
yes, just want to test first, have not found the time yet. but soon i will :+1:

**Comment by firsttris** [comment]
works very well

**Comment by firsttris** [comment]
your contribution is included in version 0.2.5.

thank you very much

**Pull request merged**
