### PR TITLE
Fix tests regex

### LINKED ISSUE #16: Test name detection fails when we use a function to construct the test
I'm using

```
it("script-empty", assertSchema("script-empty", "MyType", `No root type "MyType" found`));
```

Which runs

```
node '/Users/domoritz/Developer/UW/ts-json-schema-generator/node_modules/.bin/jest' '/Users/domoritz/Developer/UW/ts-json-schema-generator/test/invalid-data.test.ts' -t 'it("script-empty", assertSchema("script-empty", "MyType", `No root type "MyType" found`));'
```

But instead it should run 

```
node '/Users/domoritz/Developer/UW/ts-json-schema-generator/node_modules/.bin/jest' '/Users/domoritz/Developer/UW/ts-json-schema-generator/test/invalid-data.test.ts' -t 'script-empty'
```

### PR DESCRIPTION
**Pull request by domoritz**
Fixes #16

### CODE REVIEW

**Comment by domoritz** [comment]
the idea of this regex is to match until the end of the quotes string. This won't work if the test name itself contains one of those characters.

**Comment by domoritz** [comment]
For example `it("hello 'world'", () => {...})`.

**Comment by domoritz** [comment]
`(describe|it|test)\(("([^"]+)"|`([^`]+)`|'([^']+)'),` would fix this issue

**Comment by domoritz** [comment]
Okay, I'm pretty happy with the last one. Let me know if you see any issues with it. 

I know it won't work with

`it("hello\"world", ...)` but I don't think that's very common.

**Comment by firsttris** [comment]
thanks, good work, will test & merge

**Comment by domoritz** [comment]
Thanks!

**Comment by firsttris** [comment]
there was the issue that match[2] gave me ''test name'' or with your example '"script-empty"'
which did not match the test names. because of the double quotes. no clue where the double quotes come from.

so i added unquote(match[2]). 
https://github.com/firsttris/vscode-jest-runner/blob/master/src/util.ts#L46

(someone also contributed this function...)

this leads to

'test name'
'script-empty'

but acutally it should be

'test name'
"script-empty"

so i think if you use ' it will work but " will fail.

the unquote function is probably not acutally deleting the outer quotes

**Pull request merged**
