### PR TITLE
Run with CWD set to jest.config.js's parent

### PR DESCRIPTION
**Pull request by jvassev**

### CODE REVIEW

**Comment by firsttris** [comment]
thx! will have a look at it

**Comment by firsttris** [comment]
sorry for not answering so long. i have currently so many stuff in my real-life. 


not really sure what your PR is trying to fix.

**Comment by Kristof-Mattei** [comment]
@firsttris I am running into this issue as well.

Let me describe my case:

imagine trying to run in a subfolder, without `projectPath`, and you refer to a `jest.config.js` which refers to a `jest.setup.js` which then does a piece of JS that depends on the current path. 

Because node is launched from a different working dir that import will fail. 

Now, I don't think this is the correct solution. I think it should go through `projectPath`, but the problem is that that one doesn't resolve `${workspaceFolder}` and I cannot really hardcode MY path in there.

**Comment by firsttris** [comment]
i think i merged something that resolves you issues.
https://github.com/firsttris/vscode-jest-runner/commit/fa53138bbffda537390afdb1b344da4dcbe4d059

**Pull request closed without merging**
